### ISSUE TITLE
Google Home Resume: object' has no attribute 'volume_level'`

### ISSUE THREAD

**Issue by mbuurman78** [TheFes/HA-configuration#81]
First of all I want to thank you for all your work and support on all the different forums, and especially for creating these Google Resume scripts!

After upgrading HA to 2023.2 I see the following error messages in my HA Log, can you help me out to fix this?:

```
Logger: homeassistant.components.script.google_home_resume_helper
Source: helpers/script.py:409
Integration: Script (documentation, issues)
First occurred: 17:18:40 (21 occurrences)
Last logged: 21:37:34

00 - Google Home Resume - Helper Script: If at step 2: Parallel action at step 1: parallel 1: Error executing script. Error rendering template for variables at pos 3: UndefinedError: 'homeassistant.helpers.template.Wrapper object' has no attribute 'volume_level'
00 - Google Home Resume - Helper Script: If at step 2: Error executing script. Error rendering template for parallel at pos 1: UndefinedError: 'homeassistant.helpers.template.Wrapper object' has no attribute 'volume_level'
00 - Google Home Resume - Helper Script: Error executing script. Error rendering template for if at pos 2: UndefinedError: 'homeassistant.helpers.template.Wrapper object' has no attribute 'volume_level'

##############

Logger: homeassistant
Source: helpers/template.py:459
First occurred: 17:18:40 (7 occurrences)
Last logged: 21:37:34

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 457, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1984, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1465, in forgiving_round
    value = round(float(value), precision)
jinja2.exceptions.UndefinedError: 'homeassistant.helpers.template.Wrapper object' has no attribute 'volume_level'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 462, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 923, in _async_if_step
    await self._async_run_script(if_data["if_then"])
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1029, in _async_run_script
    await self._async_run_long_action(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 648, in _async_run_long_action
    long_task.result()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/trace.py", line 252, in async_wrapper
    await func(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1025, in _async_parallel_step
    raise result
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1017, in async_run_with_trace
    await self._async_run_script(script)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1029, in _async_run_script
    await self._async_run_long_action(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 648, in _async_run_long_action
    long_task.result()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 992, in _async_variables_step
    self._variables = self._action[CONF_VARIABLES].async_render(
  File "/usr/src/homeassistant/homeassistant/helpers/script_variables.py", line 62, in async_render
    rendered_variables[key] = template.render_complex(
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 156, in render_complex
    return value.async_render(variables, limited=limited, parse_result=parse_result)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 459, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'homeassistant.helpers.template.Wrapper object' has no attribute 'volume_level'```

**Comment by TheFes** [comment]
Can you send the traces for a script run when it gave this error

**Comment by mbuurman78** [comment]
updated my post, did you mean these Tracebacks?

I think some Google Home's are _unavailable_ because they are powered off when no one is in the studyroom. 
Those are the cause of the errors, I've removed those GH's from the config and the errors are gone.... 
I think I need to create a check in my automations to overcome this issue.

**Comment by TheFes** [comment]
That should be covered in the script, let me check why it isn't.
Will probably be somewhere next week though

**Comment by TheFes** [comment]
The part about the traces is explained here
https://github.com/TheFes/HA-configuration/tree/main/include/integrations/packages/google_cast#questionsissuesbugsfeature-requests

**Comment by mbuurman78** [comment]
After upgrading to 2023.2.1 the error-message has changed and tells me exactly what I already found:

```Logger: homeassistant.helpers.service
Source: helpers/service.py:640
First occurred: 17:25:20 (9 occurrences)
Last logged: 19:45:20

Unable to find referenced entities media_player.studeerkamer, media_player.zolder or it is/they are currently not available```

**Comment by TheFes** [comment]
Traces would still be helpful so I know which action causes the errors

**Comment by mbuurman78** [comment]
[trace script.google_home_resume.zip](https://github.com/TheFes/HA-configuration/files/10610792/trace.script.google_home_resume.zip)

**Comment by TheFes** [comment]
I don't think you've sent the right trace. In this trace I don't see any references to `media_player.studeerkamer` and `media_player.zolder`.
According to the data in the script, the only entity referred to as cast entity is `media_player.woonkamer`
There are also no errors in this script run.

Anyway, I think version 2023.2.0 should resolve the errors.

**Comment by mbuurman78** [comment]
In 2023.2.3 the issue popped up again, see traces:
[trace script.google_home_resume_helper.zip](https://github.com/TheFes/HA-configuration/files/10696066/trace.script.google_home_resume_helper.zip)

```Logger: homeassistant.components.script.google_home_resume_helper
Source: helpers/script.py:409
Integration: Script ([documentation](https://www.home-assistant.io/integrations/script), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+script%22))
First occurred: February 8, 2023 at 16:44:40 (24 occurrences)
Last logged: 09:41:34

00 - Google Home Resume - Helper Script: If at step 2: Parallel action at step 1: parallel 1: Error executing script. Error rendering template for variables at pos 3: UndefinedError: 'homeassistant.helpers.template.Wrapper object' has no attribute 'volume_level'
00 - Google Home Resume - Helper Script: If at step 2: Error executing script. Error rendering template for parallel at pos 1: UndefinedError: 'homeassistant.helpers.template.Wrapper object' has no attribute 'volume_level'
00 - Google Home Resume - Helper Script: Error executing script. Error rendering template for if at pos 2: UndefinedError: 'homeassistant.helpers.template.Wrapper object' has no attribute 'volume_level' ```

**Comment by TheFes** [comment]
This trace is still using version 2023.1.0
From the main script:
```
        {
          "path": "sequence/1",
          "timestamp": "2023-02-09T08:41:04.377038+00:00",
          "changed_variables": {
            "version": "2023.1.0"
          }
```

From the helper script:
```
          "changed_variables": {
            "version": "2023.1.0",
            "settings": {}
```

**Comment by mbuurman78** [comment]
Sorry, I didn't understood there was an updated version of your script. I assumed you were talking about the HA version.
Implemented version 2023.2.0 now, will keep you posted.

thx!

**Comment by TheFes** [comment]
Since I didn't hear anything, I assume this is solved now.
